### ISSUE TITLE
Feature Request : Code and Syntax Highlighting

### ISSUE THREAD

**Issue by yalh76** [gobengo/distbin#16]
I don't know if it's planned but it would be awesome to have Code and Syntax Highlighting, like describe here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

I joined an example: 
How to write a post: 
![distbin-write](https://user-images.githubusercontent.com/30271971/52236162-6387f180-28c6-11e9-8cd9-9890feda5e89.PNG)

How it could be read: 
![distbin-read](https://user-images.githubusercontent.com/30271971/52236220-887c6480-28c6-11e9-8105-718073585247.PNG)

**Comment by gobengo** [comment]
Here is where the activity.object.content gets sanitized and otherwise processed into a final html string to use on the distbin-html/an-activity pages. Easiest implementation of this would be to pass it through one more function to add syntax highlighting. https://github.com/gobengo/distbin/blob/master/src/distbin-html/an-activity.ts#L174

**Comment by yalh76** [comment]
First try to implement : https://github.com/gobengo/distbin/pull/26
